[main]
# Authentication back-end to use
auth    = htpasswd

# User DB back-end to use
userdb  = virtual

# Storage back-end to use
storage = Exim

# Who are SIEVE scripts intended for ? (Dovecot or Exim)
consumer = Exim

# Bind to what address?  (Ignored with --stdin)
#bindaddr = 127.0.0.1

# Listen on what port?  (Ignored with --stdin)
port    = 4190

# Write a pidfile here
#pidfile = /var/run/pysieved.pid
pidfile = /tmp/pysieved.pid

# Prepend this path to result of userdb lookup if not absolute
#base = /var/mail

# Where to create temporary files
#tmpdir = /tmp

# Log file
logfile = /var/log/pysieved/pysieved.log


[TLS]
# Require STARTTLS before authentication
#required = False

# TLS private key file
#key = /etc/ssl/private/woozle.org.key

# TLS certificate file
#cert = /etc/ssl/private/woozle.org.pem

# Passphrase if the TLS private key is encrypted
# (this file should not be world-readable !)
#passphrase = magic


[Virtual]
# Path to storage.  %u = user, %d = domain
path = /srv/mail/%0.1u/%u

# What domain to use if no domain name is specified by the user
defaultdomain = none.invalid

# What UID and GID should own all files?  -1 to not bother
uid = -1
gid = -1


[htpasswd]
passwdfile = /etc/dovecot/imap.passwd


[Exim]
# Path to sendmail
sendmail = /usr/sbin/sendmail

# Where in user directory to store scripts
scripts = .pysieved

# Filename used for the active SIEVE filter
active = .forward

# What user/group owns the mail storage (-1 to never setuid/setgid)
# uid = 107
# gid = 8
uid = -1
gid = -1